### PR TITLE
Support for Adafruit BSP alongside PIO BSP

### PR DESCRIPTION
**Pull request by outlandnish**
This allows the use of the Adafruit nRF52 Feather platform with `https://github.com/platformio/platform-nordicnrf52` alongside normal nRF52 boards.

### CODE REVIEW

**Comment by ivankravets** [comment]
Thank you so much for the great work!

1. I propose to keep build script for https://github.com/sandeepmistry/arduino-nRF5 without changes, it will help us to keep further maintaining
2. I recommend to avoid OOP and use plain SCons scripting. It simplifies code reading and is very simpler for people who are not good in Python
3. How about to have `arduino.py` as "entry-point" and split sub-script into `arduino` folder? See example with ST STM32 https://github.com/platformio/platform-ststm32/tree/develop/builder/frameworks

```
arduino.py
arduino/nrf5.py
arduino/adafruit.py
```

**Comment by jeremypoulter** [comment]
@nsamala Would you mind closing this PR and I will open a new one against my fork/branch. It will be easier to keep in sync with platformio/platform-nordicnrf52#23 that way?

I think I agree with @ivankravets, although the current structure is a nice split between generic Arduino stuff and the Sandeep/Adafruit BSP specific stuff probably better to follow the president set in other platforms.

**Comment by ivankravets** [comment]
I close https://github.com/platformio/platform-nordicnrf52/pull/23, let's work on the PR here. This is the right place.

**Comment by jeremypoulter** [comment]
@ivankravets, you need both, there are two parts this is about building the firmware, platformio/platform-nordicnrf52#23 is about uploading.

**Comment by outlandnish** [comment]
Yeah that's fine. Should I go ahead and close this branch?

I'm not very familiar with SCons scripting but I can give it a shot. The only caveat would be that I am a bit time limited at the moment. If you'd like me to PR to one of your branches so you can make the appropriate modifications, let me know!

**Comment by jeremypoulter** [comment]
It is basically reverting back to the the `arduino.py` and `arduino-adafruit.py` scripts, renamed to `nrf.py` and `adafruit.py` and then adding a script a level up to select which one to use (as above see https://github.com/platformio/platform-ststm32/tree/develop/builder/frameworks)

**Comment by jeremypoulter** [comment]
@nsamala I have a little time now, taking a look at the needed changes

**Comment by ivankravets** [comment]
Merged in https://github.com/platformio/builder-framework-arduino-nrf5/pull/2

**Pull request closed without merging**
